---

udev_rules_dir: /etc/udev/rules.d
# Where to install udev probe shell script
probe_bin_dir: /usr/local/sbin
# where to install backup script itself
backup_bin_dir: /usr/local/sbin
backup_config_dir: /etc/backup
# we'll be using pkg_state to remove packages
pkg_state: present
apt_packages:
  - jq
  - rsync 
rpm_packages:
  - jq
  - rsync
backup_locations:
  - /etc
  - /home